---

- name: cluster vpc
  # run locally, share facts
  <<: &run-locally
    check_mode: no
    delegate_to: local
    delegate_facts: true
    run_once: true
    tags: always
  # aws credentials
  environment: &aws-creds
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_key_id}}"
    AWS_SESSION_TOKEN: "{{aws_session_token}}"
    AWS_REGION: "{{secrets.region.primary}}"
  # TODO
  ec2_vpc_net:
    cidr_block: "{{cluster.network.cidr}}"
    dns_hostnames: yes
    dns_support: yes
    name: "{{cluster.name}}"
    tags:
      account: "{{secrets.tags.account}}"
      environment: "{{secrets.tags.environment}}"
      owner: "{{secrets.tags.owner}}"
      project: "{{secrets.tags.project}}"
  register: cluster_vpc

- name: cluster gw
  <<: *run-locally
  environment: *aws-creds
  ec2_vpc_igw:
    vpc_id: "{{cluster_vpc.vpc.id}}"
    state: present
  register: cluster_gw

- name: cluster zone
  <<: *run-locally
  environment: *aws-creds
  route53_zone:
    zone: "{{cluster.name}}"
    state: present
  register: cluster_zone

- name: debug cluster network
  <<: *run-locally
  environment: *aws-creds
  debug:
    msg: |
      vpc-id: {{cluster_vpc.vpc.id}}
      vpc-gw: {{cluster_gw.gateway_id}}
      zone-id: {{cluster_zone.result.zone_id}}
