---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-dns
  namespace: cluster-service

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-dns
  namespace: cluster-service
  labels:
    k8s-app: cluster-dns
    k8s-role: cluster-service

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

subjects:
  - kind: ServiceAccount
    name: cluster-dns
    namespace: cluster-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-dns
  namespace: cluster-service
  labels:
    k8s-app: cluster-dns
    k8s-role: cluster-service

spec:
  selector:
    matchLabels:
      k8s-app: cluster-dns

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        k8s-app: cluster-dns
      annotations:
        iam.amazonaws.com/role: "arn:aws:iam::{{ secrets.tags.account }}:role/{{ secrets.tags.project }}-cluster-dns"

    spec:
      containers:
        - name: cluster-dns
          image: "registry.opensource.zalan.do/teapot/external-dns:v0.4.8"
          args:
          - --source=service
          - --source=ingress
          - --domain-filter={{ secrets.tags.project }}.{{ secrets.dns.base }}
          - --provider=aws
          - --policy=upsert-only
          - --registry=txt
          - --txt-owner-id={{ secrets.tags.project}}.{{ secrets.dns.base }}
      nodeSelector:
        cluster: server
      serviceAccountName: cluster-dns