---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "hello-nginx"
  labels:
    app: "hello-nginx"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hello-nginx"
  template:
    metadata:
      name: "hello-nginx"
      labels:
        app: "hello-nginx"
    spec:
      containers:
        - name: "hello-nginx"
          image: "nginx:1.13-alpine"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            privileged: false
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: hello-nginx
  labels:
    app: "hello-nginx"
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: "hello-nginx"
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
