---

apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-jobs

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gitlab-runner-jobs
  namespace: gitlab-jobs
  labels:
    rbac.{{ cluster.name }}/gitlab-runner-role: "true"
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "watch", "list", "create"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gitlab-runner-default
  namespace: default
  labels:
    rbac.{{ cluster.name }}/gitlab-runner-role: "true"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.{{ cluster.name }}/gitlab-runner-role: "true"
rules: []

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: default
roleRef:
  kind: ClusterRole
  name: gitlab-runner
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-config
type: Opaque
data:
{% for name, body in gitlab.runner.config.iteritems() %}
  {{name}}: {{body.value | b64encode}}
{% endfor %}

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-data
type: Opaque
data:
  tags: {{runner_tags | b64encode}}

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secrets
  namespace: gitlab-jobs
type: Opaque
data:
{% for name, body in gitlab.runner.secrets.iteritems() %}
  {{name}}: {{body.value | b64encode}}
{% endfor %}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-runner
  labels:
    app: gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      containers:
        - name: gitlab-runner
          image: gitlab/gitlab-runner:v{{gitlab.runner.version}}
          imagePullPolicy: "Always"
          command:
            - bash
          args:
            - -c
            - /config/setup.sh
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      nodeSelector:
        cluster: server
      serviceAccountName: gitlab-runner
      volumes:
        - name: config
          secret:
            secretName: gitlab-runner-config
            items:
{% for name, body in gitlab.runner.config.iteritems() %}
              - key: {{name}}
                mode: {{body.mode}}
                path: {{body.path | default(name)}}
{% endfor %}
