---

- name: sync state variables from s3
  check_mode: no
  tags: &svc-tags
    - service-create
    - service-update
  # aws credentials
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_role_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_role_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_role_session_token }}"
    AWS_REGION: "{{secrets.region.primary}}"
  # output files
  aws_s3:
    dest: "{{output_dir.path}}/{{cluster.env}}-{{item}}.yml"
    mode: get
    bucket: "{{bucket_name}}"
    object: "{{item}}.yml"
  with_items:
    - output

- name: fetch terraform state
  check_mode: no
  tags: *svc-tags
  fetch:
    src: "{{output_dir.path}}/{{cluster.env}}-{{item}}.yml"
    dest: "{{output_dir.path}}/{{inventory_hostname}}"
    fail_on_missing: yes
    flat: yes
  with_items:
    - output

- name: load state variables
  check_mode: no
  tags: *svc-tags
  # load everything from the env dir
  include_vars:
    file: "{{output_dir.path}}/{{cluster.env}}-{{item}}.yml"
  with_items:
    - output

- name: delete state variables
  check_mode: no
  tags: *svc-tags
  # TODO
  file:
    path: "{{output_dir.path}}/{{cluster.env}}-{{item}}.yml"
    state: absent
  with_items:
    - output
