---

- name: template tfvars
  template:
    src: "{{item}}.tfvars"
    dest: "{{output_dir.path}}/tf-{{item}}.tfvars"
  with_items:
    - env
    - state
      
- name: init terraform
  shell: make terraform-create
  register: output_terraform_init

- name: init terraform output
  debug:
    var: output_terraform_init.stdout_lines

- name: plan terraform
  tags:
    - cloud-ready
  shell: make terraform-ready
  register: output_terraform_run

- name: apply terraform
  tags:
    - cloud-create
    - cloud-update
  environment:
    TF_APPROVE: -auto-approve
  shell: make terraform-update
  register: output_terraform_run

- name: terraform output
  debug:
    var: output_terraform_run.stdout_lines