---

- name: cluster version
  shell: kubectl --kubeconfig "{{ context_path }}" version | base64 | tr -d '\n'
  register: cluster_version_output

- name: debug cluster version
  debug:
    var: cluster_version_output

- name: download network
  get_url:
    url: https://cloud.weave.works/k8s/net?k8s-version={{cluster_version_output.stdout}}
    dest: "{{output_dir.path}}/k8s-network.yml"

- name: apply network
  environment:
    KUBECTL_CONTEXT: "{{ context_path }}"
    KUBECTL_RESOURCE_FILE: "{{ output_dir.path }}/k8s-network.yml"
  shell: make kubectl-apply