---

- name: set k8s context path
  check_mode: no
  tags: &svc-tags
    - service-create
    - service-ready
    - service-update
  set_fact:
    context_path: "{{output_dir.path}}/{{inventory_hostname}}-context.yml"

- name: export k8s context
  check_mode: no
  tags: *svc-tags
  # aws credentials
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_role_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_role_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_role_session_token }}"
    AWS_REGION: "{{secrets.region.primary}}"
    KUBECONFIG: "{{ context_path }}"
  shell: make kops-context

- name: load k8s context
  check_mode: no
  tags: *svc-tags
  include_vars:
    file: "{{ context_path }}"
    name: context

- name: debug k8s context
  check_mode: no
  tags: *svc-tags
  debug:
    var: context
