---
 
- name: cluster path
  check_mode: no
  file:
    state: directory
    path: "{{ output_dir.path }}/tf-cluster"

- name: template cluster
  check_mode: no
  tags:
    - cluster-create
    - cluster-update
  template:
    src: cluster.yml
    dest: "{{output_dir.path}}/k8s-cluster.yml"

- name: create cluster
  environment: &kops-env
    KOPS_DEFINITION: "{{output_dir.path}}/k8s-cluster.yml"
    KOPS_MODULE: "{{output_dir.path}}/tf-cluster"
  tags:
    - cluster-create
  shell: make kops-create
  register: cluster_output

- name: replace cluster
  tags:
    - cluster-update
  environment: *kops-env
  shell: make kops-update
  register: cluster_output

- name: cluster output
  tags:
    - cluster-update
  debug:
    var: cluster_output

- name: render terraform
  check_mode: no
  environment: *kops-env
  shell: make kops-terraform
