---

- name: download dashboard
  tags: &service-tags
    - service-create
    - service-update
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
    dest: "{{output_dir.path}}/k8s-dashboard.yml"

- name: apply dashboard
  tags: *service-tags
  shell: kubectl --kubeconfig "{{ context_path }}" apply -f {{output_dir.path}}/k8s-dashboard.yml

- name: template services
  tags: *service-tags
  template:
    src: "{{item.name}}.yml"
    dest: "{{output_dir.path}}/k8s-{{item.name}}.yml"
  with_items: "{{cluster_services}}"

- name: apply services
  tags: *service-tags
  shell: kubectl --kubeconfig "{{ context_path }}" apply -f {{output_dir.path}}/k8s-{{item.name}}.yml
  with_items: "{{cluster_services}}"
