---

- name: download dashboard
  tags: &service-tags
    - service-create
    - service-update
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
    dest: "{{output_dir.path}}/k8s-dashboard-deploy.yml"

- name: apply dashboard
  tags: *service-tags
  environment:
    KUBECTL_CONTEXT: "{{ context_path }}"
    KUBECTL_RESOURCE_FILE: "{{ output_dir.path }}/k8s-dashboard-deploy.yml"
  shell: kubectl --kubeconfig "{{ context_path }}" apply -f {{output_dir.path}}/k8s-dashboard-deploy.yml

- name: list scripts
  tags: *service-tags
  find:
    paths: "{{ build_tools_scripts.paths }}"
    patterns: 'Makefile,*.mk,*.sh'
    recurse: no
  register: script_paths

- name: read scripts
  tags: *service-tags
  set_fact:
    script_body: "{{ lookup('file', item.path) }}"
  with_items: "{{ script_paths.files }}"
  register: script_files

- name: debug scripts
  debug:
    var: script_files

- name: template services
  tags: *service-tags
  template:
    src: "{{item.name}}.yml"
    dest: "{{output_dir.path}}/k8s-{{item.name}}.yml"
  with_items: "{{cluster_services}}"

- name: apply services
  tags: *service-tags
  environment:
    KUBECTL_CONTEXT: "{{ context_path }}"
    KUBECTL_RESOURCE_FILE: "{{ output_dir.path }}/k8s-{{ item.name }}.yml"
  shell: kubectl --kubeconfig "{{ context_path }}" apply -f {{output_dir.path}}/k8s-{{item.name}}.yml
  with_items: "{{cluster_services}}"
